### ISSUE TITLE
Slideshow Height

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/bike-coop-theme#37]
From Jeff's Email (issue #36):

Reduce height of slideshow at top of page. It's taking up too much real estate and we want visitor to see that there's more to the page than the slider.

**Comment by abettermap** [comment]
@JordanMajd I dropped the height a bit on tablets and up but left it alone on phone-ish and down because it looks perf to me. I used `vw` as the height unit, so it scales vertically pretty well until you get to the big guys (1600px or so). 

If FCBC wants it narrower yet, that's fine and we can reopen this, but they may need some extremely landscape-y pics to make it look decent.
