### ISSUE TITLE
Move Wheel Buttons

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/bike-coop-theme#39]
Jeff's email (issue #36):

Move wheel icon buttons up under the top slider, see layout. Fix the arched type in the wheel buttons.

**Comment by abettermap** [comment]
> Fix the arched type in the wheel buttons.

The Stencil font is not cross platform, we will have to use `png` format instead of `SVG`

EDIT: Will try Jordan's suggestion to convert text to path...

**Comment by abettermap** [comment]
> Move wheel icon buttons up under the top slider, see layout

Layout as in this? https://github.com/CodeForFoco/bike-coop/blob/master/assets/FCBC%20Website%202_links.pdf

**Comment by abettermap** [comment]
@JordanMajd Not 100% sure what Jeff meant by "fixed arched type" but if it was font-related then we are good to go because your text-to-path suggestion worked great. If it's NOT that and they want some other fine-tuning, then we can reopen this. 

If that's the case, however, they will need to provide us with the exact graphics they want rather than just one of the three like we had at the beginning. The Inkscape workflow is tedious and messy, so I'm about spent on the damn wheels! 🚳🚳🚳 

Closed by PR #49

**Comment by JordanMajd** [comment]
Glad the text-to-path worked out!

Looks good.
